name: tests-todos

on:
  push:
    paths:
      - 'todos/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd todos && npm install && npm run test:ci
